version: '3'
services:
  staging-service:
    image: tatumio/tatum-kms
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tatumio/tatum-kms
    volumes:
      - tatum-kms-volume://var/lib/docker

volumes:
  tatum-kms-volume:
    driver: local